#@ load("@ytt:data", "data") 
---
#@ if data.values.addDB:
apiVersion: v1
data:
  rootHost: JQ==
  rootPassword: c2FraWxh
  rootUser: cm9vdA==
kind: Secret
metadata:
  name: mysql-pass
  namespace: #@ data.values.namespaceToDeploy
#@ end
---
#@ if data.values.addDB:
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: #@ data.values.dbName
  namespace: #@ data.values.namespaceToDeploy
spec:
  secretName: mysql-pass
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
  initDB:
    clone:
      donorUrl: #@ data.values.dbName+".mysql-master-ns.svc.cluster.local:3306"
      rootUser: root
      secretKeyRef:
        name: mypwds
#@ end
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.parentApp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: #@ data.values.parentApp
    #@ if data.values.hasTests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: "main"

  #@ if data.values.addDB:
  serviceClaims:
    
    #@ if data.values.addDB:
    - name: #@ data.values.dbType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.dbType 
        name: #@ data.values.dbName
    #@ end
  #@ end