#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.parentApp
  namespace: #@ data.values.namespaceToDeploy
  labels:
    #@ if data.values.dbType = mysql:
    apps.tanzu.vmware.com/workload-type: web-mysql
    #@ end
    #@ if data.values.dbType == postgres:
    apps.tanzu.vmware.com/workload-type: web-postgres
    #@ else:
    apps.tanzu.vmware.com/workload-type: web
    #@ end
    app.kubernetes.io/part-of: #@ data.values.parentApp + "-ui"
    #@ if data.values.hasTests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end

spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: #@ data.values.branchName

  #@ if data.values.addDB:
  serviceClaims:
    
    #@ if data.values.addDB:
    - name: #@ data.values.dbType + "-claim"
      ref:
        apiVersion: services.tanzu.vmware.com/v1alpha1
        kind: #@ data.values.dbType 
        name: #@ data.values.dbName
    #@ end
  #@ end