apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . }}
  labels:
    app.kubernetes.io/instance: spring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: petclinic
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: petclinic-0.1.0
    app: petclinic
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "petclinic.selectorLabels" . | nindent 4 }}
