apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-v2
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        version: v2
    spec:
      containers:
      - name: petclinic
        image: localhost:5000/spring-petclinic:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 500m
            memory: 768Mi
          limits:
            cpu: 1000m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 70
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
  type: ClusterIP
